all_workers:
  children:
    work_sa:
      hosts:
        host02:
          ansible_host: 192.168.202.2
jump_sa:
  hosts:
    bastion:
      ansible_host: 178.124.206.53
      ansible_user: jump_sa